### ISSUE TITLE
fetch_prereq requires svn

### ISSUE THREAD

**Issue by LouisStrous** [google/open-vcdiff#52]
The fetch_prereq.sh and .bat scripts to fetch prerequisite items use svn.  This means you cannot build open-vcdiff if you don't have svn installed.  Is it possible to make these prerequisites available through git instead (or also)?

**Comment by Steelskin** [comment]
Yes, this is being worked on. The issue is that we need old versions of the dependencies. Once we have updated these to a more recent version, the fetch_prereq will go away.
Currently this is blocked on using cmake to build.
